charity_bets/__init__.py
from flask import Flask, render_template
import os
from . import models
from .extensions import db, migrate, config, oauth, assets, login_manager, mail
from .views.home import home
from .views.users import users
from .views.bets import bets
from .views.charities import charities
from .views.admin import admin
from .views.charity_signup import charity_signup
import sys
import logging
from flask_sslify import SSLify

def create_app():
    app = Flask(__name__)
    app.config.from_object(__name__)

    app.config['DEBUG'] = os.environ['DEBUG']
    app.config['SECRET_KEY'] = os.environ['SECRET_KEY']
    app.config['MAIL_SERVER'] = os.environ['MAIL_SERVER']
    app.config['MAIL_PORT'] = os.environ['MAIL_PORT']
    app.config['CLIENT_ID'] = os.environ['CLIENT_ID']
    app.config['CLIENT_SECRET'] = os.environ['CLIENT_SECRET']
    # app.config['MAIL_USE_TLS'] = os.environ['MAIL_USE_TLS']
    app.config['MAIL_USE_SSL'] = os.environ['MAIL_USE_SSL']
    app.config['MAIL_USERNAME'] = os.environ['MAIL_USERNAME']
    app.config['MAIL_PASSWORD'] = os.environ['MAIL_PASSWORD']

    sslify = SSLify(app)


    app.register_blueprint(home)
    app.register_blueprint(users)
    app.register_blueprint(admin)
    app.register_blueprint(charities, url_prefix='/api')
    app.register_blueprint(charity_signup)
    app.register_blueprint(bets, url_prefix='/api')

    config.init_app(app)
    oauth.init_app(app)
    assets.init_app(app)
    mail.init_app(app)

    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)


    return app

charity_bets/views/admin.py
from flask import (session, Blueprint, url_for, request, redirect,
                   render_template, jsonify)
from flask.ext.login import current_user, login_required
from ..models import Bet, UserBet, User, Comment, Charity
from ..extensions import db
from ..forms import CharityForm
import json


admin = Blueprint("admin", __name__)

def verify_user(current_user):
    email_list = ["betsforcharity@gmail.com",
                  "bret.runestad@gmail.com",
                  "bbatty32@yahoo.com",
                  "dn78685@appstate.edu",
                  "tomrau@gmail.com"]
    if current_user.email in email_list:
        return True
    else:
        return False


@admin.route("/api/admin/user/<int:id>", methods=["DELETE"])
@login_required
def delete_user(id):
    if verify_user(current_user):
        user = User.query.get(id)
        if user:
            db.session.delete(user)
            db.session.commit()
            return jsonify({"Success": "User Deleted"})
        else:
            return jsonify({"ERROR": "Could not delete"}), 400
    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401

@admin.route("/api/admin/user/<int:id>", methods=["PUT"])
@login_required
def modify_user(id):
    if verify_user(current_user):
        user = User.query.get(id)
        if user:
            body = request.get_data(as_text=True)
            data = json.loads(body)
            keys = data.keys()
            for key in keys:
                setattr(user, key, data[key])
                db.session.commit()
            return jsonify({"data": user.make_dict()}), 201
        else:
            return jsonify({"ERROR": "No such user"}), 400
    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401

@admin.route("/api/admin/bets/<int:id>", methods=["DELETE"])
@login_required
def delete_bet(id):
    if verify_user(current_user):
        bet = Bet.query.get(id)
        if bet:
            db.session.delete(bet)
            db.session.commit()
            return jsonify({"Success": "Bet Deleted"})
        else:
            return jsonify({"ERROR": "Could not delete"}), 400
    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401

@admin.route("/api/admin/charities/<int:id>", methods=["DELETE"])
@login_required
def delete_charity(id):
    if verify_user(current_user):
        charity = Charity.query.get(id)
        if charity:
            db.session.delete(charity)
            db.session.commit()
            return jsonify({"Success": "Charity Deleted"})
        else:
            return jsonify({"ERROR": "Could not delete"}), 400
    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401

@admin.route("/api/admin/charities", methods =["GET"])
@login_required
def view_full_charities():
    if verify_user(current_user):
        charities = Charity.query.all()
        all_charities = [charity.make_dict() for charity in charities]
        return jsonify({"data": all_charities}), 201

@admin.route("/api/admin/bets", methods=["GET"])
@login_required
def really_get_all_bets():
    if verify_user(current_user):
        bets = Bet.query.all()
        all_bets = []
        for bet in bets:
            bet = bet.make_dict()
            all_bets.append(bet)
        return jsonify({"data": all_bets}), 201

    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401


@admin.route("/charities/form", methods = ["POST", "GET"])
@login_required
def post_charity():
    if verify_user(current_user):
        form = CharityForm()

        charity = Charity(name = form.name.data,
                          description=form.description.data,
                          email=form.email.data,
                          image=form.image.data,
                          website=form.website.data,
                          access_token=form.access_token.data,
                          amount_earned=form.amount_earned.data,
                          stripe_publishable_key=form.stripe_publishable_key.data,
                          stripe_user_id=form.stripe_user_id.data,
                          stripe_refresh_token=form.stripe_refresh_token.data)

        db.session.add(charity)
        db.session.commit()

        return render_template('charity_form.html', form = form)

    else:
        return jsonify({"ERROR": "Not authorized to make this request"}), 401

charity_bets/views/bets.py
from ..models import Bet, UserBet, User, Comment, Charity, Funder
from flask import (session, Blueprint, url_for, request, redirect, flash,
                    render_template, jsonify, current_app)
from ..forms import BetForm, CommentForm
from flask.ext.login import current_user, login_required
from ..extensions import db
from ..emails import (send_email, bet_creation_notification,
                       win_claim_notification, loss_claim_notification,
                       disputed_bet_notification, you_lost_notification,
                       bet_acceptance_notification, bet_canceled,
                       bet_declined)
from .fake_bet import fake_bet
import json
from charity_bets import mail
from flask_mail import Message
import stripe
from flask import current_app as app
import datetime
from sqlalchemy import or_


bets = Blueprint("bets", __name__)

def add_wins_losses(bet):
    user = User.query.filter_by(id = bet.verified_loser).first()
    user.losses = user.losses + 1
    user.win_streak = 0
    user.money_lost = user.money_lost + bet.amount

    user = User.query.filter_by(id = bet.verified_winner).first()
    user.wins = user.wins + 1
    user.win_streak = user.win_streak + 1
    if user.win_streak > user.longest_win_streak:
        user.longest_win_streak = user.win_streak
    user.money_won = user.money_won + bet.amount

def user_money_raised(bet):
    creator = User.query.filter_by(id = bet.creator).first()
    challenger = User.query.filter_by(id=bet.challenger).first()
    if creator.id == bet.verified_winner:
        creator.donation_money_raised += bet.creator_money_raised

    if challenger.id == bet.verified_winner:
        challenger.donation_money_raised += bet.challenger_money_raised


def charge_funders(bet):
    """At the resolution of the bet, this charges all the losing funders"""
    user = User.query.filter_by(id = bet.verified_winner).first()

    if user.id == bet.creator:
        charity = Charity.query.filter_by(name = bet.charity_creator).first()
    if user.id == bet.challenger:
        charity = Charity.query.filter_by(name = bet.charity_challenger).first()

    funders = Funder.query.filter_by(bet_id = bet.id,
                                     charity_token = charity.access_token).all()

    stripe.api_key = charity.access_token
    for funder in funders:
        stripe.Charge.create(
            amount = int(funder.amount)*100,
            currency = "usd",
            customer = funder.stripe_customer_id
        )

#check if a bets outcome is resolved
def check_resolution(bet):
    if bet.creator_outcome and bet.challenger_outcome:
        if bet.creator_outcome == bet.challenger_outcome:
            bet.status = "complete"
            if bet.creator_outcome == bet.creator:
                bet.verified_winner = bet.creator
                bet.verified_loser = bet.challenger
            else:
                bet.verified_winner = bet.challenger
                bet.verified_loser = bet.creator

            add_wins_losses(bet)
            user_money_raised(bet)

            bet.loser_paid = "unpaid"
            winner = User.query.filter_by(id=bet.verified_winner).first()
            bet.winner_name = winner.name

            db.session.commit()
            charge_funders(bet)

        else:
            bet.status = "conflict"
            bet.mail_track = "conflict"

            user = User.query.filter_by(id = bet.creator).first()
            user.bet_conflicts = user.bet_conflicts + 1
            user = User.query.filter_by(id = bet.challenger).first()
            user.bet_conflicts = user.bet_conflicts + 1
            db.session.commit()
    else:
        bet.status = "unresolved"
        db.session.commit()

# this needs to be tested


def bet_chart_data(bet):
    # pulls funding data for bet challenger
    challenger_funders = Funder.query.filter_by(bet_id = bet.id,
                                                is_funding = bet.challenger).all()

    challenger_donations =[{"x":0, "y": 0}]
    if challenger_funders:
        total_donations = 0
        funder_tick = 0

    for funder in challenger_funders:
        total_donations += funder.amount
        funder_tick += 1
        challenger_donations.append({"x": funder_tick, "y": total_donations})

    # pulls funding data for bet creator

    creator_funders = Funder.query.filter_by(bet_id = bet.id,
                                             is_funding = bet.creator).all()
    creator_donations =[{"x":0, "y": 0}]
    if creator_funders:
        total_donations = 0
        funder_tick = 0

    for funder in creator_funders:
        total_donations += funder.amount
        funder_tick += 1
        creator_donations.append({"x": funder_tick, "y": total_donations})

    return {"creator_data":creator_donations,
            "challenger_data":challenger_donations}


@bets.route("/user/bets", methods = ["POST"])
@login_required
def create_bet():
    body = request.get_data(as_text=True)
    data = json.loads(body)
    #  Enter Required data into Form
    form = BetForm( title=data['title'],
                    amount = int(data['amount']),
                    charity_creator = data['charity_creator'],
                    formdata=None, csrf_enabled=False)
    challenger = User.query.filter_by(name = data['challenger']).first()
    charity = Charity.query.filter_by(name = data['charity_creator']).first()

    # Validate Form
    if form.validate():
        bet = Bet(title=form.title.data,
                  amount=form.amount.data,
                  creator = current_user.id,
                  challenger = challenger.id,
                  challenger_name = challenger.name,
                  challenger_facebook_id = challenger.facebook_id,
                  creator_name = current_user.name,
                  creator_facebook_id = current_user.facebook_id,
                  charity_creator = charity.name,
                  charity_creator_id = charity.id,
                  total_money_raised = form.amount.data
                  )

        # Enter Optional Data Into Model
        if 'date' in data:
            bet.date = data['date']
        if 'description' in data:
            bet.description = data['description']
        if 'location' in data:
            bet.location = data['location']

        db.session.add(bet)
        db.session.commit()

        # Message sent to the other party of the bet
        bet_creation_notification(current_user, challenger, bet)
        bet.mail_track = "new_bet"
        db.session.add(bet)
        db.session.commit()

        user_bet = UserBet(user_id = current_user.id,
                           bet_id = bet.id)

        db.session.add(user_bet)
        db.session.commit()

        bet = bet.make_dict()

        return (jsonify({ 'data': bet }), 201)

    else:
        return form.errors, 400


def bet_aggregator(bets, bet_list):
    for a_bet in bets:
        bet = Bet.query.filter_by(id=a_bet.id).first()
        if bet:
            bet_list.append(bet)
    return bet_list

def current_user_filter(bet_status):
    return Bet.query.filter(or_(Bet.creator==current_user.id,
                                 Bet.challenger==current_user.id)
                             ).filter_by(status=bet_status).all()

@bets.route("/user/bets", methods = ["GET"])
@login_required
def view_bets():
    bets1 = current_user_filter("pending")
    bets2 = current_user_filter("active")
    bets3 = current_user_filter("unresolved")
    bets4 = current_user_filter("complete")
    bets5 = current_user_filter("conflict")
    bet_list = []
    bet_list = bet_aggregator(bets1, bet_list)
    bet_list = bet_aggregator(bets2, bet_list)
    bet_list = bet_aggregator(bets3, bet_list)
    bet_list = bet_aggregator(bets4, bet_list)
    bet_list = bet_aggregator(bets5, bet_list)
    if len(bet_list) > 0:
        bets = [bet.make_dict() for bet in bet_list]
        for bet in bets:
            if bet['challenger']==current_user.id and bet['status']=='pending':
                bet['needs_accepting'] = 'y'
            if bet['status'] == 'unresolved':
                if current_user.id != bet['creator_outcome']:
                    if current_user.id != bet['challenger_outcome']:
                        bet['maybe_you_lost'] = 'y'
                if current_user.id != bet['challenger_outcome']:
                    if current_user.id != bet['creator_outcome']:
                        bet['maybe_you_lost'] = 'y'
        return jsonify({"data": bets}), 201
    else:
        return jsonify({'data': {}})

def user_filter(bet_status, id):
    return Bet.query.filter(or_(Bet.creator==id,
                                 Bet.challenger==id)
                             ).filter_by(status=bet_status).all()

@bets.route("/user/<int:id>/bets", methods = ["GET"])
@login_required
def view_users_bets(id):
    bets1 = user_filter("active", id)
    bets2 = user_filter("complete", id)
    bets3 = user_filter("unresolved", id)
    bets4 = user_filter("pending", id)
    bet_list = []
    bet_list = bet_aggregator(bets1, bet_list)
    bet_list = bet_aggregator(bets2, bet_list)
    bet_list = bet_aggregator(bets3, bet_list)
    bet_list = bet_aggregator(bets4, bet_list)
    if len(bet_list) > 0:
        bets = [bet.make_dict() for bet in bet_list]
        return jsonify({"data": bets }), 201
    else:
        return jsonify({'data': {}})


@bets.route("/bets", methods = ["GET"])
@login_required
def view_all_bets():
    bets = Bet.query.order_by(Bet.amount.desc()).all()
    all_bets = [bet.make_dict() for bet in bets]
    all_bets = [bet for bet in all_bets if bet["status"]!='conflict']
    if bets:
        return jsonify({'data': all_bets}), 201
    else:
        return jsonify({'data': {}})

@bets.route("/bets/<filter>/<sorter>", methods = ["GET"])
@login_required
def view_filtered_sorted_bets(filter, sorter):
    if filter == "all":
        bets = Bet.query.order_by((getattr(Bet, sorter)).desc()).all()
    else:

charity_bets/views/fake_bet.py
from ..models import Bet, User, Charity
from flask.ext.login import current_user

def fake_bet():
    betti = User.query.filter_by(email="betsforcharity@gmail.com").first()
    fake_bet = Bet(title="Sample Bet",
                  id = 0,
                  amount=20,
                  creator = betti.id,
                  challenger = current_user.id,
                  challenger_name = current_user.name,
                  challenger_facebook_id = current_user.facebook_id,
                  challenger_outcome = current_user.id,
                  charity_challenger = "The charity of your choice",
                  charity_challenger_id = 999,
                  creator_name = "Betti",
                  creator_facebook_id = betti.facebook_id,
                  creator_outcome = current_user.id,
                  charity_creator = "The Human Fund",
                  charity_creator_id = 2,
                  status = "complete",
                  date = "2020-01-01T04:00:00.000Z",
                  description = "More details about your bet!",
                  location = "The place where your bet will happen",
                #   verified_winner = current_user.id,
                #   verified_loser = betti.id,
                #   winner_name = current_user.name
                  )
    return fake_bet

def fake_charity():
    fake_charity = Charity(name="Sample Charity",
                           id=0)
    return fake_charity

charity_bets/views/home.py
from flask import Blueprint, flash


home = Blueprint("home", __name__, static_folder="../static")


@home.route("/")
def index():
    return home.send_static_file("index.html")

charity_bets/templates/accepted_bet_email.html
<p>Dear {{ creator.name}},</p>
<p>{{ challenger.name }} has accepted your bet on betti!</p>
<p> View your bet at:</p>
<a href="http://betti.co/email/{{ bet.id }}">{{ bet.title }}</a><br />


<p>Good luck,</p>
<p>The betti team</p>

charity_bets/templates/canceled_bet_email.html
<p>Dear {{ challenger.name}},</p>

<p>{{ creator.name }} has canceled your bet, {{ bet.title }}, on betti.</p>
<p>Maybe you didn't respond in time, or maybe {{ challenger.name }} got scared.</p>

<p>Either way, go ahead and make another bet at:</p>
<a href="http://betti.co/email/{{ bet.id }}">betti.co</a><br />


<p>Good luck,</p>
<p>The betti team</p>

charity_bets/templates/charity_form.html
{% block body %}

      <h1>Charity Info</h1>
      <table>
      <form method="POST" action="{{ url_for("admin.post_charity") }}">
        {{ form.hidden_tag() }}
          <div class="row">
            <div>
              {{ form.name.label }} {{ form.name(size=50) }}
            </div>
          <br>
          <div>
              {{ form.description.label }} {{ form.description(size=50) }}
          </div>
          <br>
          <div>
              {{ form.email.label }} {{ form.email(size=50) }}
          </div>
          <br>
          <div>
              {{ form.image.label }} {{ form.image(size=50) }}
          </div>
          <br>
          <div>
              {{ form.website.label }} {{ form.website(size=50) }}
          </div>
          <br>
          <div>
              {{ form.access_token.label }} {{ form.access_token(size=50) }}
          </div>
          <br>
          <div>
              {{ form.amount_earned.label }} {{ form.amount_earned(size=50) }}
          </div>
          <br>
          <div>
              {{ form.stripe_publishable_key.label }} {{ form.stripe_publishable_key(size=50) }}
          </div>
          <br>
          <div>
              {{ form.stripe_user_id.label }} {{ form.stripe_user_id(size=50) }}
          </div>
          <br>
          <div>
              {{ form.stripe_refresh_token.label }} {{ form.stripe_refresh_token(size=50) }}
          </div>
          <br><br><br>

          <input type="submit" value="Submit" class="button round">
        </div>
      </form>


{% endblock %}

charity_bets/templates/charity_signup.html
<!doctype html>



  <head>
    <title>Stripe OAuth Example</title>
    <link rel="stylesheet" href="/static/css/main.css">
  </head>
  <body>
  

    <div class="charity-signup">
      <a href="/authorize"><button class="charity-button">Connect your non-profit with Betti</button></a>
    </div>
  </body>
</html>

charity_bets/templates/declined_bet_email.html
<p>Dear {{ creator.name}},</p>
<p>{{ challenger.name }} has declined your bet, {{ bet.title }} on betti.</p>
<p>Don't be discouraged!  Make another bet at:</p>

<a href="http:/betti.co/#/createbet">betti.co</a><br />


<p>Good luck,</p>
<p>The betti team</p>

charity_bets/templates/did_you_lose_email.html
<p>Dear {{ loser.name}},</p>
<p>{{ winner.name }} has claimed victory in your bet on betti!</p>
<p>Click the link below to view your bet:</p>
<a href="http://localhost:5000/email/{{ bet.id }}">{{ bet.title }}</a><br />

<p>If you accept defeat, please promptly follow the directions to reward {{ winner_charity }} with ${{ bet.amount }} via stripe.</p>
<p>And remember, this was for charity!  So even in losing, you win, because you're giving to a great cause!</p>


<p>Thanks,</p>
<p>The betti team</p>

charity_bets/templates/disputed_bet_email.html
<p>Dear {{ recipient.name }},</p>
<p>Sadly, you and {{ opponent.name }} have been unable to agree on the resolution of your betti bet:
<a href="http://localhost:5000/email/{{ bet.id }}">{{ bet.title }}</a><br /></p>
<p>betti is a fun website designed to direct money to charity in a new way.
  We are not in the business of trying to investigate or determine who was the actual winner of the bet.</p>

<p>Because you failed to reach a bet resolution, no charities will receive any donations!</p>
<p>Hopefully on your next betti bet, you'll be able to reach a better outcome.</p>

<p>Thanks,</p>
<p>The betti team</p>

charity_bets/templates/duplicate.html
<!doctype html>
  <head>
    <title>Stripe OAuth Example</title>
  </head>
  <body>
    <b>Error:<b/> A charity with that email is already registered in the database.
  </body>
</html>

charity_bets/templates/new_bet_email.html
<p>Dear {{ challenger.name}},</p>
<p>{{ creator.name }} has challenged you to a bet on betti!</p>
<p> View your bet at:</p>
<a href="http://localhost:5000/email/{{ bet.id }}">{{ bet.title }}</a><br />


<p>Good luck,</p>
<p>The betti team</p>

charity_bets/templates/thank_you.html
<!doctype html>
  <head>
    <title>Signup Complete!</title>
  </head>
  <body>
    Thank You!
  </body>
</html>

charity_bets/templates/you_lost_email.html
<p>Dear {{ loser.name}},</p>
<p>Your bet with {{ winner.name }} on betti is over, and you, alas, have lost.</p>
<p>Click the link below to view your bet:</p>
<a href="http://betti.co/email/{{ bet.id }}">{{ bet.title }}</a><br />

<p>Thank you for rewarding {{ winner_charity }} with ${{ bet.amount }} via stripe.</p>
<p>Again, we're sorry that you lost, but happy that {{ winner_charity }} is a little richer.</p>


<p>Thanks,</p>
<p>The betti team</p>

charity_bets/templates/you_won_email.html
<p>Dear {{ winner.name }},</p>
<p>Congratulations! {{ loser.name }} has conceded victory in your bet on betti!</p>
<p> View your bet at:</p>
<a href="http://betti.co/email/{{ bet.id }}">{{ bet.title }}</a><br />
<p>Your chosen charity of {{ winner_charity }} has earned ${{ bet.amount }} and you're not a penny poorer!</p>

<p>Good luck,</p>
<p>The betti team</p>